// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_r_png);   // assets/R.png
LV_IMG_DECLARE( ui_img_checkmark_circle_png);   // assets/checkmark.circle.png
LV_IMG_DECLARE( ui_img_623366413);   // assets/image-2.png
LV_IMG_DECLARE( ui_img_image_png);   // assets/image.png
LV_IMG_DECLARE( ui_img_812009816);   // assets/image-3.png
LV_IMG_DECLARE( ui_img_2079530671);   // assets/image-4.png
LV_IMG_DECLARE( ui_img_lungs_png);   // assets/lungs.png
LV_IMG_DECLARE( ui_img_exclamationmark_circle_png);   // assets/exclamationmark.circle.png

// FONTS
LV_FONT_DECLARE( ui_font_SFpro);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
