// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Abnormal = NULL;lv_obj_t *ui_TextArea5 = NULL;lv_obj_t *ui_Image8 = NULL;
// event funtions
void ui_event_Abnormal( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Connected, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Connected_screen_init);
}
}

// build funtions

void ui_Abnormal_screen_init(void)
{
ui_Abnormal = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Abnormal, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Abnormal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Abnormal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea5 = lv_textarea_create(ui_Abnormal);
lv_obj_set_width( ui_TextArea5, 320);
lv_obj_set_height( ui_TextArea5, 100);
lv_obj_set_x( ui_TextArea5, lv_pct(0) );
lv_obj_set_y( ui_TextArea5, lv_pct(27) );
lv_obj_set_align( ui_TextArea5, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea5,"Abnormal Lung Sounds");
lv_textarea_set_placeholder_text(ui_TextArea5,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea5, &ui_font_SFpro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea5, &ui_font_SFpro, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Abnormal);
lv_img_set_src(ui_Image8, &ui_img_exclamationmark_circle_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image8, lv_pct(0) );
lv_obj_set_y( ui_Image8, lv_pct(-15) );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image8,225);

lv_obj_add_event_cb(ui_Abnormal, ui_event_Abnormal, LV_EVENT_ALL, NULL);

}

void ui_Abnormal_screen_destroy(void)
{
   if (ui_Abnormal) lv_obj_del(ui_Abnormal);

// NULL screen variables
ui_Abnormal= NULL;
ui_TextArea5= NULL;
ui_Image8= NULL;

}
