// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Complete = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_TextArea1 = NULL;
// event funtions
void ui_event_Complete( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Connected, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Connected_screen_init);
}
}

// build funtions

void ui_Complete_screen_init(void)
{
ui_Complete = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Complete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Complete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Complete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Complete);
lv_img_set_src(ui_Image2, &ui_img_checkmark_circle_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image2, lv_pct(0) );
lv_obj_set_y( ui_Image2, lv_pct(-15) );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,250);

ui_TextArea1 = lv_textarea_create(ui_Complete);
lv_obj_set_width( ui_TextArea1, 320);
lv_obj_set_height( ui_TextArea1, 100);
lv_obj_set_x( ui_TextArea1, lv_pct(0) );
lv_obj_set_y( ui_TextArea1, lv_pct(27) );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea1,"Recording Complete");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SFpro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SFpro, LV_PART_SELECTED| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Complete, ui_event_Complete, LV_EVENT_ALL, NULL);

}

void ui_Complete_screen_destroy(void)
{
   if (ui_Complete) lv_obj_del(ui_Complete);

// NULL screen variables
ui_Complete= NULL;
ui_Image2= NULL;
ui_TextArea1= NULL;

}
