// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Connected = NULL;lv_obj_t *ui_TextArea2 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Image5 = NULL;
// event funtions
void ui_event_Connected( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Recording, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Recording_screen_init);
}
}

// build funtions

void ui_Connected_screen_init(void)
{
ui_Connected = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Connected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Connected, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Connected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea2 = lv_textarea_create(ui_Connected);
lv_obj_set_width( ui_TextArea2, 320);
lv_obj_set_height( ui_TextArea2, 101);
lv_obj_set_x( ui_TextArea2, lv_pct(0) );
lv_obj_set_y( ui_TextArea2, lv_pct(25) );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea2,"Soniscope Connected");
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea2, &ui_font_SFpro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea2, &ui_font_SFpro, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Connected);
lv_img_set_src(ui_Image3, &ui_img_623366413);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image3, lv_pct(-28) );
lv_obj_set_y( ui_Image3, lv_pct(-10) );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,150);

ui_Image4 = lv_img_create(ui_Connected);
lv_img_set_src(ui_Image4, &ui_img_image_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 183
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 38
lv_obj_set_x( ui_Image4, lv_pct(0) );
lv_obj_set_y( ui_Image4, lv_pct(-10) );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,100);

ui_Image5 = lv_img_create(ui_Connected);
lv_img_set_src(ui_Image5, &ui_img_812009816);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 237
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 259
lv_obj_set_x( ui_Image5, lv_pct(25) );
lv_obj_set_y( ui_Image5, lv_pct(-10) );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,150);

lv_obj_add_event_cb(ui_Connected, ui_event_Connected, LV_EVENT_ALL, NULL);

}

void ui_Connected_screen_destroy(void)
{
   if (ui_Connected) lv_obj_del(ui_Connected);

// NULL screen variables
ui_Connected= NULL;
ui_TextArea2= NULL;
ui_Image3= NULL;
ui_Image4= NULL;
ui_Image5= NULL;

}
