// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COMPLETE_H
#define UI_COMPLETE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Complete
extern void ui_Complete_screen_init(void);
extern void ui_Complete_screen_destroy(void);
extern void ui_event_Complete( lv_event_t * e);
extern lv_obj_t *ui_Complete;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

