// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CONNECTED_H
#define UI_CONNECTED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connected
extern void ui_Connected_screen_init(void);
extern void ui_Connected_screen_destroy(void);
extern void ui_event_Connected( lv_event_t * e);
extern lv_obj_t *ui_Connected;
extern lv_obj_t *ui_TextArea2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

