// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HEALTHY_H
#define UI_HEALTHY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Healthy
extern void ui_Healthy_screen_init(void);
extern void ui_Healthy_screen_destroy(void);
extern void ui_event_Healthy( lv_event_t * e);
extern lv_obj_t *ui_Healthy;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

