// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Healthy = NULL;lv_obj_t *ui_TextArea4 = NULL;lv_obj_t *ui_Image7 = NULL;
// event funtions
void ui_event_Healthy( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Connected, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Connected_screen_init);
}
}

// build funtions

void ui_Healthy_screen_init(void)
{
ui_Healthy = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Healthy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Healthy, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Healthy, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea4 = lv_textarea_create(ui_Healthy);
lv_obj_set_width( ui_TextArea4, 320);
lv_obj_set_height( ui_TextArea4, 100);
lv_obj_set_x( ui_TextArea4, lv_pct(0) );
lv_obj_set_y( ui_TextArea4, lv_pct(27) );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea4,"Healthy");
lv_textarea_set_placeholder_text(ui_TextArea4,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea4, &ui_font_SFpro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea4, &ui_font_SFpro, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Healthy);
lv_img_set_src(ui_Image7, &ui_img_lungs_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 258
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 189
lv_obj_set_x( ui_Image7, lv_pct(0) );
lv_obj_set_y( ui_Image7, lv_pct(-15) );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image7,225);

lv_obj_add_event_cb(ui_Healthy, ui_event_Healthy, LV_EVENT_ALL, NULL);

}

void ui_Healthy_screen_destroy(void)
{
   if (ui_Healthy) lv_obj_del(ui_Healthy);

// NULL screen variables
ui_Healthy= NULL;
ui_TextArea4= NULL;
ui_Image7= NULL;

}
