// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Home = NULL;lv_obj_t *ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Home);
lv_img_set_src(ui_Image1, &ui_img_r_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 500
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 500
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
ui_Home= NULL;
ui_Image1= NULL;

}
