// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Recording = NULL;lv_obj_t *ui_TextArea3 = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Spinner1 = NULL;
// event funtions
void ui_event_Recording( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
}
}

// build funtions

void ui_Recording_screen_init(void)
{
ui_Recording = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Recording, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Recording, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Recording, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Recording);
lv_obj_set_width( ui_TextArea3, 320);
lv_obj_set_height( ui_TextArea3, 70);
lv_obj_set_x( ui_TextArea3, lv_pct(0) );
lv_obj_set_y( ui_TextArea3, lv_pct(25) );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea3,"Recording");
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea3, &ui_font_SFpro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextArea3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextArea3, &ui_font_SFpro, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Recording);
lv_img_set_src(ui_Image6, &ui_img_2079530671);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 227
lv_obj_set_x( ui_Image6, lv_pct(0) );
lv_obj_set_y( ui_Image6, lv_pct(-15) );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image6,225);

ui_Spinner1 = lv_spinner_create(ui_Recording,1000,90);
lv_obj_set_width( ui_Spinner1, 360);
lv_obj_set_height( ui_Spinner1, 360);
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x6AC6DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xF67C2E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Recording, ui_event_Recording, LV_EVENT_ALL, NULL);

}

void ui_Recording_screen_destroy(void)
{
   if (ui_Recording) lv_obj_del(ui_Recording);

// NULL screen variables
ui_Recording= NULL;
ui_TextArea3= NULL;
ui_Image6= NULL;
ui_Spinner1= NULL;

}
