// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Open_Screen.h"
#include "ui_Recording_Complete.h"
#include "ui_Recording.h"
#include "ui_Sleep.h"
#include "ui_Connected.h"
#include "ui_Recording_Incomplete.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * sec_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * min_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * hour_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * left_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * right_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * opa_on_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * dots_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * top_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * cloud_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * blood2_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * blood1_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * heart_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * BluetoothConnection_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * recording_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * wavy_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_977762417);   // assets/R (1).png
LV_IMG_DECLARE( ui_img_1279885393);   // assets/Screenshot 2025-07-18 at 9.57.02 AM.png
LV_IMG_DECLARE( ui_img_waveform_path_png);   // assets/waveform.path.png
LV_IMG_DECLARE( ui_img_moon_zzz_png);   // assets/moon.zzz.png
LV_IMG_DECLARE( ui_img_ellipsis_png);   // assets/ellipsis.png
LV_IMG_DECLARE( ui_img_iphone_gen3_png);   // assets/iphone.gen3.png
LV_IMG_DECLARE( ui_img_stethoscope_circle_png);   // assets/stethoscope.circle.png
LV_IMG_DECLARE( ui_img_exclamationmark_triangle_png);   // assets/exclamationmark.triangle.png
LV_IMG_DECLARE( ui_img_btn_bg_1_png);   // assets/btn_bg_1.png
LV_IMG_DECLARE( ui_img_btn_bg_3_png);   // assets/btn_bg_3.png
LV_IMG_DECLARE( ui_img_call1_png);   // assets/call1.png

// FONTS
LV_FONT_DECLARE( ui_font_H1);
LV_FONT_DECLARE( ui_font_Number_big);
LV_FONT_DECLARE( ui_font_Number_extra);
LV_FONT_DECLARE( ui_font_Subtitle);
LV_FONT_DECLARE( ui_font_Title);
LV_FONT_DECLARE( ui_font_SF_Compact);
LV_FONT_DECLARE( ui_font_SF_Pro);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
