// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_CONNECTED_H
#define UI_CONNECTED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connected
extern void ui_Connected_screen_init(void);
extern void ui_Connected_screen_destroy(void);
extern lv_obj_t *ui_Connected;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

