// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Connected = NULL;lv_obj_t *ui_TextArea1 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Image4 = NULL;
// event funtions

// build funtions

void ui_Connected_screen_init(void)
{
ui_Connected = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Connected, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Connected, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Connected, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea1 = lv_textarea_create(ui_Connected);
lv_obj_set_width( ui_TextArea1, 251);
lv_obj_set_height( ui_TextArea1, 83);
lv_obj_set_x( ui_TextArea1, lv_pct(0) );
lv_obj_set_y( ui_TextArea1, lv_pct(28) );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea1,"Soniscope Connected");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SF_Pro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea1, &ui_font_SF_Compact, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image2 = lv_image_create(ui_Connected);
lv_image_set_src(ui_Image2, &ui_img_ellipsis_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 183
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 38
lv_obj_set_x( ui_Image2, lv_pct(2) );
lv_obj_set_y( ui_Image2, lv_pct(-12) );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image2,80);

ui_Image3 = lv_image_create(ui_Connected);
lv_image_set_src(ui_Image3, &ui_img_iphone_gen3_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 126
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 207
lv_obj_set_x( ui_Image3, lv_pct(24) );
lv_obj_set_y( ui_Image3, lv_pct(-12) );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image3,150);

ui_Image4 = lv_image_create(ui_Connected);
lv_image_set_src(ui_Image4, &ui_img_stethoscope_circle_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_Image4, lv_pct(-24) );
lv_obj_set_y( ui_Image4, lv_pct(-13) );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image4,150);

}

void ui_Connected_screen_destroy(void)
{
   if (ui_Connected) lv_obj_del(ui_Connected);

// NULL screen variables
ui_Connected= NULL;
ui_TextArea1= NULL;
ui_Image2= NULL;
ui_Image3= NULL;
ui_Image4= NULL;

}
