// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_OPEN_SCREEN_H
#define UI_OPEN_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Open_Screen
extern void ui_Open_Screen_screen_init(void);
extern void ui_Open_Screen_screen_destroy(void);
extern lv_obj_t *ui_Open_Screen;
extern lv_obj_t *ui_Image8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

