// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Open_Screen = NULL;lv_obj_t *ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Open_Screen_screen_init(void)
{
ui_Open_Screen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Open_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Open_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Open_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_image_create(ui_Open_Screen);
lv_image_set_src(ui_Image8, &ui_img_977762417);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 500
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 500
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Open_Screen_screen_destroy(void)
{
   if (ui_Open_Screen) lv_obj_del(ui_Open_Screen);

// NULL screen variables
ui_Open_Screen= NULL;
ui_Image8= NULL;

}
