// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_RECORDING_INCOMPLETE_H
#define UI_RECORDING_INCOMPLETE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Recording_Incomplete
extern void ui_Recording_Incomplete_screen_init(void);
extern void ui_Recording_Incomplete_screen_destroy(void);
extern lv_obj_t *ui_Recording_Incomplete;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

