// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_RECORDING_H
#define UI_RECORDING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Recording
extern void ui_Recording_screen_init(void);
extern void ui_Recording_screen_destroy(void);
extern lv_obj_t *ui_Recording;
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Spinner2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

