// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Recording = NULL;lv_obj_t *ui_TextArea3 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Spinner2 = NULL;
// event funtions

// build funtions

void ui_Recording_screen_init(void)
{
ui_Recording = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Recording, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Recording, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Recording, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Recording);
lv_obj_set_width( ui_TextArea3, 209);
lv_obj_set_height( ui_TextArea3, 70);
lv_obj_set_x( ui_TextArea3, lv_pct(0) );
lv_obj_set_y( ui_TextArea3, lv_pct(28) );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea3,"Recording");
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea3, &ui_font_SF_Pro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_Recording);
lv_image_set_src(ui_Image1, &ui_img_waveform_path_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 227
lv_obj_set_x( ui_Image1, lv_pct(0) );
lv_obj_set_y( ui_Image1, lv_pct(-16) );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,200);

ui_Spinner2 = lv_spinner_create(ui_Recording);
//lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
lv_obj_set_width( ui_Spinner2, 360);
lv_obj_set_height( ui_Spinner2, 360);
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x83D2E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_scale(ui_Spinner2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xFF8500), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}

void ui_Recording_screen_destroy(void)
{
   if (ui_Recording) lv_obj_del(ui_Recording);

// NULL screen variables
ui_Recording= NULL;
ui_TextArea3= NULL;
ui_Image1= NULL;
ui_Spinner2= NULL;

}
