// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_RECORDING_COMPLETE_H
#define UI_RECORDING_COMPLETE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Recording_Complete
extern void ui_Recording_Complete_screen_init(void);
extern void ui_Recording_Complete_screen_destroy(void);
extern lv_obj_t *ui_Recording_Complete;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_TextArea2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

