// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Recording_Incomplete = NULL;lv_obj_t *ui_TextArea4 = NULL;lv_obj_t *ui_Image6 = NULL;
// event funtions

// build funtions

void ui_Recording_Incomplete_screen_init(void)
{
ui_Recording_Incomplete = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Recording_Incomplete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Recording_Incomplete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Recording_Incomplete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea4 = lv_textarea_create(ui_Recording_Incomplete);
lv_obj_set_width( ui_TextArea4, 249);
lv_obj_set_height( ui_TextArea4, 83);
lv_obj_set_x( ui_TextArea4, lv_pct(0) );
lv_obj_set_y( ui_TextArea4, lv_pct(28) );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea4,"Recording Failed");
lv_textarea_set_placeholder_text(ui_TextArea4,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea4, &ui_font_SF_Pro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea4, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea4, &ui_font_SF_Compact, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Image6 = lv_image_create(ui_Recording_Incomplete);
lv_image_set_src(ui_Image6, &ui_img_exclamationmark_triangle_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 205
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 187
lv_obj_set_x( ui_Image6, lv_pct(0) );
lv_obj_set_y( ui_Image6, lv_pct(-16) );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image6,200);

}

void ui_Recording_Incomplete_screen_destroy(void)
{
   if (ui_Recording_Incomplete) lv_obj_del(ui_Recording_Incomplete);

// NULL screen variables
ui_Recording_Incomplete= NULL;
ui_TextArea4= NULL;
ui_Image6= NULL;

}
