// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Recording_Complete = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_TextArea2 = NULL;
// event funtions

// build funtions

void ui_Recording_Complete_screen_init(void)
{
ui_Recording_Complete = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Recording_Complete, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Recording_Complete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Recording_Complete, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_image_create(ui_Recording_Complete);
lv_image_set_src(ui_Image5, &ui_img_1279885393);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 452
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 400
lv_obj_set_x( ui_Image5, lv_pct(0) );
lv_obj_set_y( ui_Image5, lv_pct(-16) );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image5,200);

ui_TextArea2 = lv_textarea_create(ui_Recording_Complete);
lv_obj_set_width( ui_TextArea2, 249);
lv_obj_set_height( ui_TextArea2, 83);
lv_obj_set_x( ui_TextArea2, lv_pct(0) );
lv_obj_set_y( ui_TextArea2, lv_pct(28) );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea2,"Recording Complete");
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea2, &ui_font_SF_Pro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea2, &ui_font_SF_Compact, LV_PART_SELECTED| LV_STATE_DEFAULT);

}

void ui_Recording_Complete_screen_destroy(void)
{
   if (ui_Recording_Complete) lv_obj_del(ui_Recording_Complete);

// NULL screen variables
ui_Recording_Complete= NULL;
ui_Image5= NULL;
ui_TextArea2= NULL;

}
