// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "ui.h"

lv_obj_t *ui_Sleep = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_TextArea6 = NULL;
// event funtions

// build funtions

void ui_Sleep_screen_init(void)
{
ui_Sleep = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Sleep, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Sleep, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Sleep, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_image_create(ui_Sleep);
lv_image_set_src(ui_Image7, &ui_img_moon_zzz_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 196
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 243
lv_obj_set_x( ui_Image7, lv_pct(0) );
lv_obj_set_y( ui_Image7, lv_pct(-16) );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image7,200);

ui_TextArea6 = lv_textarea_create(ui_Sleep);
lv_obj_set_width( ui_TextArea6, 249);
lv_obj_set_height( ui_TextArea6, 83);
lv_obj_set_x( ui_TextArea6, lv_pct(0) );
lv_obj_set_y( ui_TextArea6, lv_pct(28) );
lv_obj_set_align( ui_TextArea6, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea6,"Sleeping");
lv_textarea_set_placeholder_text(ui_TextArea6,"Placeholder...");
lv_obj_set_style_text_color(ui_TextArea6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextArea6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea6, &ui_font_SF_Pro, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_TextArea6, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea6, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea6, &ui_font_SF_Compact, LV_PART_SELECTED| LV_STATE_DEFAULT);

}

void ui_Sleep_screen_destroy(void)
{
   if (ui_Sleep) lv_obj_del(ui_Sleep);

// NULL screen variables
ui_Sleep= NULL;
ui_Image7= NULL;
ui_TextArea6= NULL;

}
