// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_SLEEP_H
#define UI_SLEEP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sleep
extern void ui_Sleep_screen_init(void);
extern void ui_Sleep_screen_destroy(void);
extern lv_obj_t *ui_Sleep;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_TextArea6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

